server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET:change-this-to-a-long-random-secret-key-min-32-characters}

management.endpoints.web.exposure.include=health,info,gateway
spring.main.web-application-type=reactive
